### PR TITLE
Define CXXFLAGS also on Windows for consistency with Unix builds

### PR DESCRIPTION
**Pull request by traversaro**
On Linux and macOS builds, the PCL build system does not attempt to add any SEE, AVX or similar custom option as there is a `CXXFLAGS` environment variable is set, and hence the CMake variable `CMAKE_CXX_FLAGS` has not its default value, see:
* https://github.com/PointCloudLibrary/pcl/blob/pcl-1.13.1/CMakeLists.txt#L104
* https://github.com/PointCloudLibrary/pcl/blob/pcl-1.13.1/CMakeLists.txt#L116
* https://github.com/PointCloudLibrary/pcl/blob/pcl-1.13.1/CMakeLists.txt#L150

On Windows, no CXXFLAGS environment variable is defined, so some flags that change the ABI of the Eigen library as passed to the compilaton. This is problematic when ones tries to link an executable with PCL while also linking other libraries that also compiled with Eigen, but using the default ABI of conda-forge builds. 

So, to make sure that PCL treats Windows builds as Linux builds without changing the Eigen ABI w.r.t. to other conda-forge packages, we define the CXXFLAGS environment variable also on Windows, setting in it an harmless option (i.e. [`/nologo`](https://learn.microsoft.com/en-us/cpp/build/reference/nologo-suppress-startup-banner-c-cpp?view=msvc-170))

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@pcl-feedstock the PR is ready for review.

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Hi @traversaro - looking at it again, you define CXXFLAGS with CXXFLAGS - I’m not a Win expert, is that as intended? If so, I’m happy to merge.

**Comment by traversaro** [comment]
> Hi @traversaro - looking at it again, you define CXXFLAGS with CXXFLAGS - I’m not a Win expert, is that as intended? If so, I’m happy to merge.

Yes, sorry I should have provided more details. Basically I am pre-pending the `/nologo` option to any `CXXFLAGS` value that could be set in the future by compiler activation scripts. In this way, we ensure that CXXFLAGS is always defined, as opposed to just setting `CXXFLAGS` to `/nologo` that would silently suppress any option set by the compiler activation scripts in the future.

**Comment by traversaro** [comment]
I just realized that with this PR we also probably broke ABI of the Windows 1.13.0, my bad. Anyhow if we soon merge https://github.com/conda-forge/pcl-feedstock/pull/55 this should not be a big problem as for this package we have `run_exports: - {{ pin_subpackage('pcl', max_pin='x.x.x') }}`

**Pull request merged**
