### PR TITLE
Add aarch and ppc64le support

### LINKED ISSUE #24: Why is ppc64le disabled?
Is there a specific technical reason for not enabling ppc64le for this feedstock?

Thanks!

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #24

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Both aarch and ppc builds are timing out. @isuruf suggested cross-compilation on gitter, but I have no experience in settings this up - I'll leave this PR here in case someone wants to take over.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Beautiful - cross-compilation was much easier than expected :+1: . This is ready to be merged @hobu @chambbj

**Comment by Tobias-Fischer** [comment]
Kind ping @conda-forge/pcl @hobu @chambbj :)

**Comment by chambbj** [comment]
Thanks for the contribution @Tobias-Fischer!

**Pull request merged**
