### PR TITLE
Boost174

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Fix #25

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @hobu @chambbj @CJ-Wright @wolfv

**Comment by hobu** [comment]
Thanks so much 🙏

**Comment by hobu** [comment]
@Tobias-Fischer if you are a frequent PCL user and are willing, please add yourself to the maintainers in a new PR. @chambbj and I are not close followers of PCL anymore, and we are also no longer direct users of it. We're happy to push the Merge button, but maintainers that know the current state of the library in relation to Conda are going to be more current with updates.

**Comment by hobu** [comment]
ah, you did it already! Thanks 🙏

**Pull request merged**
