### PR TITLE
Rebuild for vtk930 and migrate from qt-main (qt5) to qt6-main

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I did this assuming that the qt of vtk and qt of pcl could be difference, but that is not the case: in code like https://github.com/PointCloudLibrary/pcl/blob/b0b25194f214112e3eb3db876f33960fd85f5794/apps/cloud_composer/src/items/fpfh_item.cpp#L36-L37 the two are interacting and expected to be the same version. At this point, probably we can just to switch to use qt6-main .

**Comment by traversaro** [comment]
Last failure:

~~~
[ 35%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/interactor_style.cpp.o
/Users/runner/miniforge3/conda-bld/pcl_1718805078887/work/visualization/src/interactor_style.cpp:613:19: error: 'exists' is unavailable: introduced in macOS 10.15 - see https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
      if (pcl_fs::exists (camera_file_))
                  ^
/Users/runner/miniforge3/conda-bld/pcl_1718805078887/work/visualization/src/interactor_style.cpp:613:27: error: '~path' is unavailable: introduced in macOS 10.15 - see https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
      if (pcl_fs::exists (camera_file_))
                          ^
/Users/runner/miniforge3/conda-bld/pcl_1718805078887/_build_env/bin/../include/c++/v1/__filesystem/path.h:509:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
3 errors generated.
make[2]: *** [visualization/CMakeFiles/pcl_visualization.dir/build.make:90: visualization/CMakeFiles/pcl_visualization.dir/src/interactor_style.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1204: visualization/CMakeFiles/pcl_visualization.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/deprecations.py", line 71, in inner
    return func(*args, **kwargs)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 593, in main
    execute(sys.argv[1:])
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 572, in execute
    outputs = api.build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/api.py", line 254, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 3789, in build_tree
    packages_from_this = build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 2670, in build
    utils.check_call_env(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 435, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 411, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/pcl_1718805078887/work/conda_build.sh']' returned non-zero exit status 2.
~~~

not sure why it was not appening before as 10.12 was fixed. Anyhow, we can skip this checks as described in https://conda-forge.org/docs/maintainer/knowledge_base/#newer-c-features-with-old-sdk .

**Comment by traversaro** [comment]
@conda-forge/pcl the PR is ready for review.

**Comment by Tobias-Fischer** [comment]
Thanks a lot @traversaro! This looks good - however, should we try and build ppc with qt6 support? I think it’s available if I’m not mistaken. If it works out of the box I’d suggest to enable support; if it doesn’t, then let’s keep it as is. What do you think?

**Comment by traversaro** [comment]
> Thanks a lot @traversaro! This looks good - however, should we try and build ppc with qt6 support? I think it’s available if I’m not mistaken. If it works out of the box I’d suggest to enable support; if it doesn’t, then let’s keep it as is. What do you think?

Looking at https://anaconda.org/conda-forge/qt6-main it does not seem that `linux-ppc64le` is available?

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Thanks for checking - all good then on my side. Will merge unless there are objections in the next 48 hours.

**Comment by traversaro** [comment]
It seems no one is against this, fyi @Tobias-Fischer .

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
