### PR TITLE
Add vtk to build visualization

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This is needed to build rtabmap in the RoboStack project
/cc @wolfv @traversaro

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by hobu** [comment]
I'm worried that VTK and QT dependencies of PCL are going to make it difficult to bump versions and rerender in the future. VTK and QT (QT especially) are not upgraded at their normal release pace in Conda/Forge.  

I don't know if it is possible to create a sub package or something that makes this part of PCL optionally installed. It is probably a lot more effort than it is worth.

**Comment by Tobias-Fischer** [comment]
We can create two variants, one with QT/VTK and one without. I'll try getting it to build first, and then introduce the variant.

**Comment by hobu** [comment]
If it is a big hassle don't worry about it.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Is there some way to enforce pulling in the most recent build? Osx fails because it pulls in the previous build of vtk (build num 6), not the very latest build (build num 7)

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @hobu @chambbj,
This is now ready for your review. It adds support for the `visualization` subsystem by enabling the `WITH_OPENGL`, `WITH_QT` and `WITH_VTK` flags. To enable building with VTK9, a patch is included from https://github.com/PointCloudLibrary/pcl/pull/4262 that is already merged upstream.

It would be great if you could have a look and let me know what you think.

**Review by chambbj — APPROVED** [review]
I'm fine with this. Objections @hobu?

**Comment by chambbj** [comment]
@Tobias-Fischer I guess I will only add that it could be helpful to cross-reference the patch to the PCL fix so that it is a little more obvious when we can back out the patch. E.g., patch `4540` corresponds to https://github.com/PointCloudLibrary/pcl/pull/4540 and has yet to be merged. I'll be honest, we clearly haven't been great about watching these, but it could help down the road.

**Pull request merged**
