### PR TITLE
Add patch to find full path to FLANN

### PR DESCRIPTION
**Pull request by chambbj**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chambbj** [comment]
@conda-forge-admin please rerender

**Comment by chambbj** [comment]
@hobu Can you see anything obviously wrong with the FLANN patch I'm trying to apply here?

**Comment by Tobias-Fischer** [comment]
Is that PR still needed @hobu @chambbj?

**Comment by chambbj** [comment]
You can close it. I don’t remember the history and things seem to be
building fine without it.

**Pull request closed without merging**
