### PR TITLE
Fix qhull not being found

### LINKED ISSUE #29: Regression: qhull not found
For some reason, in recent builds that pull in qhull 2020.2, we get 
```
-- Could NOT find Qhull (missing: QHULL_LIBRARIES QHULL_INCLUDE_DIRS) 
```
whereas previously with qhull 2019.1, we got 
```
-- Found Qhull: optimized;$PREFIX/lib/libqhull_p.so;debug;$PREFIX/lib/libqhull_p.so  
-- QHULL found (include: $PREFIX/include, lib: optimized;$PREFIX/lib/libqhull_p.so;debug;$PREFIX/lib/libqhull_p.so)
```

So probably there's an issue with the new version of qhull. Should we pin to the old version until we figure out what's wrong there? The issue is that certain header files (e.g. convex_hull.h) are not being created at the moment.

/cc @wolfv @conda-forge/qhull

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #29

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
qhull is now found correctly after pinning:
```
-- Found Qhull: optimized;$PREFIX/lib/libqhull_p.so;debug;$PREFIX/lib/libqhull_p.so  
-- QHULL found (include: $PREFIX/include, lib: optimized;$PREFIX/lib/libqhull_p.so;debug;$PREFIX/lib/libqhull_p.so)
```

I would say let's merge this, and then we can remove the pin once https://github.com/conda-forge/qhull-feedstock/issues/12 is resolved

**Comment by Tobias-Fischer** [comment]
Thanks to @traversaro's comments in https://github.com/conda-forge/qhull-feedstock/issues/12 I decided to go for the proper fix instead, i.e. backporting https://github.com/PointCloudLibrary/pcl/pull/4540

It finds QHull correctly, let's see whether the build passes.

**Comment by Tobias-Fischer** [comment]
This is now ready to be merged @hobu @chambbj

**Comment by chambbj** [comment]
Thanks again @Tobias-Fischer. Glad to see this is at least on the path to being fixed in PCL already.

**Pull request merged**
