### PR TITLE
Rebuildboost cpp 1.70.00

### PR DESCRIPTION
**Pull request by looooo**
continued from https://github.com/conda-forge/pcl-feedstock/pull/16

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
Azure now worked. Interesting. So switching back to azure.

**Comment by looooo** [comment]
@mariusvniekerk ca you review and merge?

**Comment by looooo** [comment]
@hobu @chambbj is it possible to merge this PR?

**Comment by hobu** [comment]
@looooo any chance you'd be willing to pick up maintenance on this feedstock? Neither @chambbj nor I use this in our projects and we aren't tracking it that closely.

**Comment by looooo** [comment]
I never used this library and I don't know anything about it. There is an optional dependency of freecad on pcl which I would like to enable. This is the only reason why I care about updating to boot 1.70.
Anyway, feel free to add me to the maintainer's list.

**Comment by hobu** [comment]
> I never used this library and I don't know anything about it. 

That's our problem too! 😄 

We'll wait until someone comes along who is connected to the project or has a hard dependency on it. No need to burden you 😉

**Pull request merged**
