### PR TITLE
pin-compatible, use boost-cpp instead of boost

### PR DESCRIPTION
**Pull request by dougalsutherland**
About `boost`:

- The naming is confusing, but the `boost` package includes `boost::python`; you should only need `boost-cpp` here.

- The `boost-cpp` (and `boost`) recipes don't have a `pin_run_as_build` entry (yet – https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/58), and so you need to explicitly `pin_compatible` to ensure that a compatible version of the library is used at runtime as at build time.

- I removed the `skip` for `py!=36`; as-is, I think it would have been impossible to install on python2.7 on Linux, for example. I'm allowing a `vc9` build here, but if that fails we can skip it with <code>skip: true&nbsp; # [vc9]</code>.

cc @scopatz, FYI.

### CODE REVIEW

**Comment by chambbj** [comment]
@dougalsutherland The `py!=36` skip was I'm sure a holdover from earlier fumbling with PDAL. No need to limit here IMO. `vc9` however does appear to be an issue. As for Travis, the PCL builds do tend to timeout from time to time, not sure what to do about that here.

**Comment by scopatz** [comment]
Yeah, this naming scheme always gets me. Thanks for the reminder @dougalsutherland!

**Comment by dougalsutherland** [comment]
We can avoid Travis timeouts by [using Circle for OSX](https://conda-forge.org/docs/ciservices.html#using-circle-for-both-linux-and-osx), which has a longer timeout. :)

Also skipped VC9 since that seems to not work. I guess the AppVeyor build for VC14 also timed out, though; not sure if there's anything we can do about that....

**Comment by jakirkham** [comment]
Could use `jom` or `ninja` instead of `nmake` to get parallel builds on Windows.

**Comment by jakirkham** [comment]
FYI - CircleCI macOS builds are slowed.

ref: https://fleep.io/chat?cid=Bzl9QQa9T0q3jFeLMwdvtQ

**Comment by chambbj** [comment]
I must be missing something. Looks like Appveyor is still trying to build `vc9`. 🤔

**Comment by dougalsutherland** [comment]
Huh, I thought that worked but obviously didn't check properly. This will.

Also switching to `ninja install` to try to speed up Windows build.

**Comment by msarahan** [comment]
vc9 doesn't work because that's a variable that isn't defined.  vc is defined, because it is part of conda_build_config.yaml.

py35 and such were hard-coded.  https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L99

I probably won't maintain the hardcoded crap going forward.

**Comment by jakirkham** [comment]
That or we could do this...

> It would be nice if things like `np110` were interpreted as `np==110` as might be reasonably expected.

xref: https://github.com/conda/conda-build/issues/1202

**Pull request merged**
